name: CI (Prebuilt I2P Router Workflow)

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

    # uses github.com/go-i2p/i2p-provider
jobs:
  i2p-router-integration:
    name: Reusable router workflow (${{ matrix.backend }})
    strategy:
      fail-fast: false
      matrix:
        backend:
          - java
          - i2pd
    uses: go-i2p/i2p-provider/.github/workflows/i2p-router.yml@main
    with:
      backend: ${{ matrix.backend }}

  test:
    name: go-i2cp test suite (${{ matrix.backend }})
    needs: i2p-router-integration
    strategy:
      fail-fast: false
      matrix:
        backend:
          - java
          - i2pd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - run: go test -v -timeout 20m -count=1 ./...
